config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash'

  get '/login',     :to => 'sessions#login'
  post '/sessions', :to => 'sessions#create'
  get '/logout',    :to => 'sessions#logout'

  resources :orders
  resources :organizations do
    resources :events
  end
  resources :products
  resources :users

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :organization

  has_many :products
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_organization

  # GET /events
  # GET /events.json
  def index
    @events = @organization.events.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @products = @event.products
  end

  # GET /events/new
  def new
    @event = @organization.events.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

      if @event.save
        redirect_to organization_path(@event.organization), notice: 'Event was successfully created.'
      else
        render :new
      end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if @event.update(event_params)
      redirect_to organization_path(@event.organization), notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    redirect_to organization_url(@organization), notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    def set_organization
      @organization = current_user.organizations.where(id: params[:organization_id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_at, :end_at, :name, :organization_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= form_for @event, url: organization_event_path(@organization, @event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', organization_event_path(@event.organization, @event) %> |
<%= link_to 'Back', organization_events_path(@organization) %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Events</h1>

<table>
  <thead>
    <tr>
      <th>Start at</th>
      <th>End at</th>
      <th>Name</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.start_at %></td>
        <td><%= event.end_at %></td>
        <td><%= event.name %></td>
        <td><%= event.organization_id %></td>
        <td><%= link_to 'Show', organization_event_path(event.organization, event) %></td>
        <td><%= link_to 'Edit', edit_organization_event_path(event.organization, event) %></td>
        <td><%= link_to 'Destroy', organization_event_path(event.organization, event), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_organization_event_path(@organization) %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= form_for @event, url: organization_events_path(@organization) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_at %><br>
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <%= f.hidden_field :organization_id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', organization_events_path(@organization) %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start at:</strong>
  <%= @event.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @event.end_at %>
</p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<%= link_to 'Edit', edit_organization_event_path(@event.organization, @event) %> |
<%= link_to 'Back', organization_events_path(@organization) %>

<h3>All Products:</h3>

<table>
<tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= link_to 'Show', organization_product_path(product.organization, product) %></td>
      <td><%= link_to 'Edit', edit_organization_product_path(product.organization, product) %></td>
      <td><%= link_to 'Destroy', organization_product_path(product.organization, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</tbody>
</table>

<%= link_to 'New Product', new_organization_product_path(@organization) %>