config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash'

  get '/login',     :to => 'sessions#login'
  post '/sessions', :to => 'sessions#create'
  get '/logout',    :to => 'sessions#logout'

  resources :orders
  resources :organizations do
    resources :events
  end
  resources :products
  resources :users

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_many :products

  has_many :user_organizations
  has_many :users, through: :user_organizations

  has_many :events
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]
  before_filter :authorize

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = current_user.organizations
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @events = @organization.events
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    if @organization.save
      current_user.organizations << @organization

      redirect_to @organization, notice: 'Organization was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    if @organization.update(organization_params)
      redirect_to @organization, notice: 'Organization was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    redirect_to organizations_url, notice: 'Organization was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = current_user.organizations.where(id: params[:id]).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form' %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Organizations</h1>


 <!--  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->





  <br>

  <%= link_to 'New Organization', new_organization_path %>

  <!-- Page Content -->
  <div class="container">

    <!-- Page Header -->
    <div class="row">
      <div class="col-lg-12">
        <h1 class="page-header">Page Heading
          <small>Secondary Text</small>
        </h1>
      </div>
    </div>
    <!-- /.row -->

    <!-- Projects row -->
    <div class="row">
      <% @organizations.each do |organization| %>
      <div class="col-md-4 portfolio-item">
        <a href="<%= organization_path(organization) %>">
         <img class="img-responsive" src="http://placehold.it/700x400" alt="">
       </a>
       <a href="<%= organization_path(organization) %>"><h3><%= organization.name %></h3></a>
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae.</p>
       <%= link_to 'Show', organization %>
       <br>
       <%= link_to 'Edit', edit_organization_path(organization) %>
       <br>
       <%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %>
     </div>
     <% end %>
   </div>


 </div>
 <!-- /.container -->

app/views/organizations/new.html.erb
<div class="row">
	<div class="col-md-4"></div>

	<%= form_for(@organization) do |f| %>
		<div class="col-md-4">
				<h3>Create Your Organization</h3>
				<%= f.label :name %><br>
				<%= f.text_field :name, class: "form-control" %><br>
				<!-- this is supposed to be description -->
				<%= f.label :name %><br>
				<%= f.text_field :name, class: "form-control" %><br>
				<!--  -->
				<input type="file" name="pic" accept="image/*"><br>
				<%= f.submit 'Submit', class: "btn btn-danger" %><br>				
		</div>
	<% end %>
	<div class="col-md-4"></div>
</div>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %>

    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Events</p>
                <div class="list-group">
                <% @events.each do |event| %>
                    <a href="#" data-event-id="<%= event.id %>" class="list-group-item event"><%= event.name %></a>
                <% end %>
                </div>
                <div>
                <%= link_to 'New Event', new_organization_event_path(@organization) %>
                </div>
            </div>

            <div class="col-md-9">

                <div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="http://placehold.it/800x300" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>

                </div>

                <div class="row" id="products">
                </div>
                <%= link_to 'New Product', new_product_path %>
            </div>

        </div>

    </div>
    <!-- /.container -->