config/routes.rb
Rails.application.routes.draw do
  root 'pages#splash'

  get '/login',     :to => 'sessions#login'
  post '/sessions', :to => 'sessions#create'
  get '/logout',    :to => 'sessions#logout'

  resources :orders
  resources :organizations do
    resources :events
  end
  resources :products
  resources :users

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :event
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    event = Event.find(params[:event_id])
    @products = event.products

    render json: @products
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    if @product.save
      respond_to do |format|
        format.html { redirect_to organization_path(@product.event.organization_id) }
        format.json { render json: @product }
      end
    else
      raise 'thom is not awake yet'
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    if @product.update(product_params)
      render json: @product
    else
      raise 'thom is not awake yet'
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    render json: @product
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:image, :description, :price, :event_id, :name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
	def current_events
		organizations = current_user.organizations
		Event.where(organization_id: organizations.map(&:id))
	end
end

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= form_for @product, url: organization_product_path(@organization, @product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', organization_product_path(@product.organization, @product) %> |
<%= link_to 'Back', organization_products_path(@organization) %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Image</th>
      <th>Description</th>
      <th>Price</th>
      <th>Organization</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.image %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.organization_id %></td>
        <td><%= link_to 'Show', organization_product_path(product.organization, product) %></td>
        <td><%= link_to 'Edit', edit_organization_product_path(product.organization, product) %></td>
        <td><%= link_to 'Destroy', organization_product_path(product.organization, product), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_organization_product_path(@organization) %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for @product, url: products_path do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.select :event_id, current_events.map {|e| [e.name, e.id] } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>